version: '3.8'

services:
  pgdatabase:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s 
      retries: 5
    restart: always
    ports:
      - "5435:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  ingest_data:
    build:
      context: .
      dockerfile: Dockerfile # path to your Dockerfile
    environment:
      - DB_HOST=pgdatabase
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ny_taxi
    depends_on:
      - pgdatabase
    restart: on-failure
 